version: "3.9"
services:
  db-mysql:
    image: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=azota
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "D:/My projects/Web/azota/azota_db"

  redis_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "D:/My projects/Web/azota/redis_data"
