export const GRADE_OPTIONS = [
  { name: "Khối 1", value: "0" },
  { name: "Khối 2", value: "1" },
  { name: "Khối 3", value: "2" },
  { name: "Khối 4", value: "3" },
  { name: "Khối 5", value: "4" },
  { name: "Khối 6", value: "5" },
  { name: "Khối 7", value: "6" },
  { name: "Khối 8", value: "7" },
  { name: "Khối 9", value: "8" },
  { name: "Khối 10", value: "9" },
  { name: "Khối 11", value: "10" },
  { name: "Khối 12", value: "11" },
  { name: "Khác", value: "12" },
];

export const SUBJECT_OPTIONS = [
  { name: "Âm nhạc", value: "0" },
  { name: "Mỹ thuật", value: "1" },
  { name: "Công nghệ", value: "2" },
  { name: "Giáo dục kinh tế và Pháp luật", value: "4" },
  { name: "Giáo dục Quốc phòng và an ninh", value: "5" },
  { name: "Giáo dục thể chất", value: "6" },
  { name: "Hóa học", value: "7" },
  { name: "Lịch sử", value: "8" },
  { name: "Địa lý", value: "9" },
  { name: "Nghệ thuật", value: "10" },
  { name: "Ngoại ngữ 1", value: "11" },
  { name: "Ngoại ngữ 2", value: "12" },
  { name: "Ngữ Văn", value: "13" },
  { name: "Sinh học", value: "14" },
  { name: "Tiếng Dân tộc thiểu số", value: "15" },
  { name: "Tin học", value: "16" },
  { name: "Toán", value: "17" },
  { name: "Vật lý", value: "18" },
  { name: "Giáo dục công dân", value: "19" },
  { name: "Khác", value: "20" },
];

export const PURPOSE_OPTIONS = [
  { name: "Ôn tập theo chương bài", value: "0" },
  { name: "Kiểm tra giữa kỳ I", value: "1" },
  { name: "Kiểm tra cuối kỳ I", value: "2" },
  { name: "Khác", value: "3" },
  { name: "Ôn tập theo chương bài", value: "4" },
  { name: "Kiểm tra giữa kỳ II", value: "5" },
  { name: "Kiểm tra cuối kỳ II", value: "6" },
  { name: "Khác", value: "7" },
  { name: "Thi tốt nghiệp THPT", value: "8" },
  { name: "Thi vào Lớp 10", value: "9" },
  { name: "Thi vào Lớp 6", value: "10" },
  { name: "Ôn tập theo chương bài", value: "11" },
  { name: "Khác", value: "12" },
];
